platform :ios, '8.0'

target 'GeneralProjectKit' do
   pod 'MJExtension', '~> 3.0.10'   
   pod 'MJRefresh', '~> 3.1.0'
   pod 'AFNetworking', '~> 3.1.0'
   pod 'SDWebImage', '~> 3.7.6'
   pod 'UMengAnalytics','~>4.2.4'#标准SDK，含IDFA
   pod 'Realm', '~> 2.7.0'
   pod 'RBQFetchedResultsController', '~> 5.0.2'
   pod 'IQKeyboardManager', '~> 4.0.9'
   pod 'FDFullscreenPopGesture', '~> 1.1'
end
