platform :ios, '8.0'

target 'GeneralProjectKit' do
   pod 'MJExtension', '~> 3.0.10'   
   pod 'MJRefresh', '~> 3.1.0'
   pod 'AFNetworking', '~> 3.1.0'
   pod 'SDWebImage', '~> 3.7.6'
   pod 'Realm'
   pod 'RBQFetchedResultsController'
   pod 'IQKeyboardManager'
end
